version: "3"
services:
  app:
    container_name: prog_Conighi
    build: .
    command: nodemon --watch /usr/src/app -e js app.js
    ports:
      - "3000:3000"
    volumes:
      - ./app:/usr/src/app
    links:
      - "mongo_Conighi:mongohost"
  mongo_Conighi:
    container_name: mongo_Conighi
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - '27017:27017'